### ISSUE TITLE
可不可以用cron表达式指定什么时候运行

### ISSUE THREAD

**Issue by kkAtGithub** [SuperNG6/docker-bilbili-helper#5]
如题
现在的这种调度方式总感觉不太方便，如果大佬有时间的话可不可以支持cron呢？

**Comment by SuperNG6** [comment]
已添加

`CRON=true`禁用task，使用cron
手动编辑`/config/bh-crontab`文件，重启容器后生效

**Comment by kkAtGithub** [comment]
哇大佬真的太快啦！感谢🙏

**Comment by kkAtGithub** [comment]
好像没用呀。。。
加上环境变量cron=true之后也没禁用task，看日志还是一天后再签到，而且到了crontab指定的时间日志里也没签到的记录

**Comment by kkAtGithub** [comment]
这是docker-compose文件的内容
  bilbili-helper:
    image: superng6/bilbili-helper:latest
    container_name: bilbili-helper
    environment:
      - CUSP=true
      - CRON=true
      - TZ=UTC
    volumes:
      - ./bilihelper/config:/config
    restart: unless-stopped   

时区是UTC
bilbili-helper.log:
==================2020/11/30 01:55:57==================
==========今天已签到完毕，下次签到时间为1d后===========

bh-crontab:
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
0       2       *       *       *       bash /app-conf/bh-run.sh

到指定的时间后并没有签到~~

**Comment by kkAtGithub** [comment]
把环境变量TZ=UTC去掉之后crontab生效了
===========检查CRON定时任务===========
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
5       10       *       *       *       bash /app-conf/bh-run.sh

===========已启动定时任务===========
===========刚启动容器时为上次的运行日志，定时任务完成后日志会刷新===========
2020-11-30 09:55:53 INFO  : -----漫画权益领取开始-----
2020-11-30 09:55:53 INFO  : 本日非执行日期
2020-11-30 09:55:53 INFO  : -----任务结束-----

2020-11-30 09:55:53 INFO  : 本日任务已全部执行完毕
2020-11-30 09:55:54 INFO  : 今日获得的总经验值为: 15
2020-11-30 09:55:54 INFO  : 当前等级Lv6，经验值为：37762
2020-11-30 09:55:57 INFO  : 任务状态推送成功
==================2020/11/30 01:55:57==================
==========今天已签到完毕，下次签到时间为1d后===========

**Comment by SuperNG6** [comment]
你的docker-compose都写错了
- TZ=Asia/Shanghai
 ````
version: "3"
services:
  bilbili-helper:
    image: superng6/bilbili-helper:latest
    container_name: bilbili-helper
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - TASK=1d
      - DEDEUSERID=1
      - SESSDATA=2
      - BILI_JCT=3
#     - SERVERPUSHKEY=token
      - CUSP=true
      - CRON=true
    volumes:
      - /appdata/config:/config
    restart: unless-stopped

````
